### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [CCninja86/KiwiBug#3]
Hi,

I don't know the license of this code, but here I assume this is free software (e.g. GNU GPL v3)

Are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind, that do not use Google Play nor anything else, except F-Droid.

You can find some documentation [here](https://f-droid.org/docs/).

**Comment by CCninja86** [comment]
Not sure about this yet. This was a university project and is far from being complete. It's only open-source so that I can use it in my CV.

**Comment by Poussinou** [comment]
OK. If you want to add this app (and the other one you have build) in F-Droid one day, feel free to do it, even if they aren't totally complete. If they are functional, that's enough :)
You can ping me if you need help :)

By the way, you should add an open-source license to all your repos, so that is clear they are. You can choose one [here](https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses). (Personnaly, I prefer GNU GPL v3)
